version: '2'
services:
  app:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: watchexec -i "dist/*" -e js,ts -r yarn build:babel && yarn start